export const API_URL = process.env.VUE_APP_API_URL;


export const ENDPOINT_INICIO_SESION = process.env.VUE_APP_ENDPOINT_INICIO_SESION;
export const ENDPOINT_LISTAR_PROVEEDORES = process.env.VUE_APP_ENDPOINT_LISTAR_PROVEEDORES;
export const ENDPOINT_AGREGAR_PROVEEDOR = process.env.VUE_APP_ENDPOINT_AGREGAR_PROVEEDOR;
export const ENDPOINT_ELIMINAR_PROVEEDOR = process.env.VUE_APP_ENDPOINT_ELIMINAR_PROVEEDOR;
export const ENDPOINT_EDITAR_PROVEEDOR = process.env.VUE_APP_ENDPOINT_EDITAR_PROVEEDOR;
export const ENDPOINT_BUSCAR_PROVEEDOR = process.env.VUE_APP_ENDPOINT_BUSCAR_PROVEEDOR;
export const ENDPOINT_CONSULTAR_PROVEEDOR = process.env.VUE_APP_ENDPOINT_CONSULTAR_PROVEEDOR;

export const ENDPOINT_LISTAR_SUBCATEGORIAS = process.env.VUE_APP_ENDPOINT_LISTAR_SUBCATEGORIAS;
export const ENDPOINT_LISTAR_SUBCATEGORIAS_POR_CATEGORIAS = process.env.VUE_APP_ENDPOINT_LISTAR_SUBCATEGORIAS_POR_CATEGORIAS;
export const ENDPOINT_AGREGAR_SUBCATEGORIA = process.env.VUE_APP_ENDPOINT_AGREGAR_SUBCATEGORIA;
export const ENDPOINT_ELIMINAR_SUBCATEGORIA = process.env.VUE_APP_ENDPOINT_ELIMINAR_SUBCATEGORIA;
export const ENDPOINT_EDITAR_SUBCATEGORIA = process.env.VUE_APP_ENDPOINT_EDITAR_SUBCATEGORIA;
export const ENDPOINT_BUSCAR_SUBCATEGORIA = process.env.VUE_APP_ENDPOINT_BUSCAR_SUBCATEGORIA;
export const ENDPOINT_CONSULTAR_SUBCATEGORIA = process.env.VUE_APP_ENDPOINT_CONSULTAR_SUBCATEGORIA;

export const ENDPOINT_LISTAR_USUARIOS = process.env.VUE_APP_ENDPOINT_LISTAR_USUARIOS;
export const ENDPOINT_AGREGAR_USUARIO = process.env.VUE_APP_ENDPOINT_AGREGAR_USUARIO;
export const ENDPOINT_ELIMINAR_USUARIO = process.env.VUE_APP_ENDPOINT_ELIMINAR_USUARIO;
export const ENDPOINT_EDITAR_USUARIO = process.env.VUE_APP_ENDPOINT_EDITAR_USUARIO;
export const ENDPOINT_BUSCAR_USUARIO = process.env.VUE_APP_ENDPOINT_BUSCAR_USUARIO;
export const ENDPOINT_CONSULTAR_USUARIO = process.env.VUE_APP_ENDPOINT_CONSULTAR_USUARIO;

export const ENDPOINT_LISTAR_CATEGORIAS = process.env.VUE_APP_ENDPOINT_LISTAR_CATEGORIAS;
export const ENDPOINT_AGREGAR_CATEGORIA = process.env.VUE_APP_ENDPOINT_AGREGAR_CATEGORIA;
export const ENDPOINT_ELIMINAR_CATEGORIA = process.env.VUE_APP_ENDPOINT_ELIMINAR_CATEGORIA;
export const ENDPOINT_EDITAR_CATEGORIA = process.env.VUE_APP_ENDPOINT_EDITAR_CATEGORIA;
export const ENDPOINT_BUSCAR_CATEGORIA = process.env.VUE_APP_ENDPOINT_BUSCAR_CATEGORIA;
export const ENDPOINT_CONSULTAR_CATEGORIA = process.env.VUE_APP_ENDPOINT_CONSULTAR_CATEGORIA;


export const ENDPOINT_LISTAR_PRODUCTOS = process.env.VUE_APP_ENDPOINT_LISTAR_PRODUCTOS;
export const ENDPOINT_AGREGAR_PRODUCTO = process.env.VUE_APP_ENDPOINT_AGREGAR_PRODUCTO;
export const ENDPOINT_ELIMINAR_PRODUCTO = process.env.VUE_APP_ENDPOINT_ELIMINAR_PRODUCTO;
export const ENDPOINT_EDITAR_PRODUCTO = process.env.VUE_APP_ENDPOINT_EDITAR_PRODUCTO;
export const ENDPOINT_BUSCAR_PRODUCTO = process.env.VUE_APP_ENDPOINT_BUSCAR_PRODUCTO;
export const ENDPOINT_CONSULTAR_PRODUCTO = process.env.VUE_APP_ENDPOINT_CONSULTAR_PRODUCTO;
export const ENDPOINT_LISTAR_PRODUCTO_POR_CATEGORIA = process.env.VUE_APP_ENDPOINT_LISTAR_PRODUCTO_POR_CATEGORIA;

export const ENDPOINT_LISTAR_SOLICITUDES_ENTRE_FECHAS = process.env.VUE_APP_ENDPOINT_LISTAR_SOLICITUDES_ENTRE_FECHAS;
export const ENDPOINT_LISTAR_SOLICITUDES = process.env.VUE_APP_ENDPOINT_LISTAR_SOLICITUDES;
export const ENDPOINT_CONSULTAR_SOLICITUD = process.env.VUE_APP_ENDPOINT_CONSULTAR_SOLICITUD;
export const ENDPOINT_AGREGAR_SOLICITUD = process.env.VUE_APP_ENDPOINT_AGREGAR_SOLICITUD;

export const ENDPOINT_AGREGAR_MOVIMIENTO = process.env.VUE_APP_ENDPOINT_AGREGAR_MOVIMIENTO;
export const ENDPOINT_LISTAR_MOVIMIENTOS = process.env.VUE_APP_ENDPOINT_LISTAR_MOVIMIENTOS;
export const ENDPOINT_VER_MOVIMIENTO = process.env.VUE_APP_ENDPOINT_VER_MOVIMIENTO;

export const ENDPOINT_AGREGAR_FECHA = process.env.VUE_APP_ENDPOINT_AGREGAR_FECHA;
export const ENDPOINT_LISTAR_FECHAS = process.env.VUE_APP_ENDPOINT_LISTAR_FECHAS;
export const ENDPOINT_VER_FECHA = process.env.VUE_APP_ENDPOINT_VER_FECHA;

export const ENDPOINT_LISTAR_ENTRADAS = process.env.VUE_APP_ENDPOINT_LISTAR_ENTRADAS;
export const ENDPOINT_AGREGAR_ENTRADA = process.env.VUE_APP_ENDPOINT_AGREGAR_ENTRADA;
export const ENDPOINT_LISTAR_SALIDAS = process.env.VUE_APP_ENDPOINT_LISTAR_SALIDAS;

export const ENDPOINT_ENVIAR_CORREO = process.env.VUE_APP_ENDPOINT_ENVIAR_CORREO;

export const ENDPOINT_LISTAR_CUENTAS = process.env.VUE_APP_ENDPOINT_LISTAR_CUENTAS;
export const ENDPOINT_CONSULTAR_CUENTA = process.env.VUE_APP_ENDPOINT_CONSULTAR_CUENTA;

