export const API_URL = process.env.VUE_APP_API_URL;
export const ENDPOINT_INICIO_SESION = process.env.VUE_APP_ENDPOINT_INICIO_SESION;
export const ENDPOINT_LISTAR_PROVEEDORES = process.env.VUE_APP_ENDPOINT_LISTAR_PROVEEDORES;
export const ENDPOINT_AGREGAR_PROVEEDOR = process.env.VUE_APP_ENDPOINT_AGREGAR_PROVEEDOR;
export const ENDPOINT_ELIMINAR_PROVEEDOR = process.env.VUE_APP_ENDPOINT_ELIMINAR_PROVEEDOR;
export const ENDPOINT_EDITAR_PROVEEDOR = process.env.VUE_APP_ENDPOINT_EDITAR_PROVEEDOR;
export const ENDPOINT_BUSCAR_PROVEEDOR = process.env.VUE_APP_ENDPOINT_BUSCAR_PROVEEDOR;
