export const API_URL = process.env.VUE_APP_API_URL;
export const ENDPOINT_INICIO_SESION = process.env.VUE_APP_ENDPOINT_INICIO_SESION;
export const ENDPOINT_LISTAR_PROVEEDORES = process.env.VUE_APP_ENDPOINT_LISTAR_PROVEEDORES;
export const ENDPOINT_AGREGAR_PROVEEDOR = process.env.VUE_APP_ENDPOINT_AGREGAR_PROVEEDOR;
